export const personalEnum = {
  last_name: "last_name",
  first_name: "first_name",
  pesel: "pesel",
  date_of_birth: "date_of_birth",
  place_of_birth: "place_of_birth",
  gender: "gender",
  phone_number: "phone_number",
  email: "email",
  street: "street",
  street_number: "street_number",
  apartment_number: "apartment_number",
  city: "city",
  zip_code: "zip_code",
  county: "county",
  community: "community",
  voivodeship: "voivodeship",
  mailing_address: "mailing_address",
  mailing_street: "mailing_street",
  mailing_street_number: "mailing_street_number",
  mailing_apartment_number: "mailing_apartment_number",
  mailing_city: "mailing_city",
  mailing_zip_code: "mailing_zip_code",
  mailing_county: "mailing_county",
  mailing_community: "mailing_community",
  mailing_voivodeship: "mailing_voivodeship",
  black_list: "black_list",
  marketing_agreement: "marketing_agreement",
  shipping_agreement: "shipping_agreement",
  assigned_project: "assigned_project",
  sub_region: "sub_region",
  osi: "osi",
  zit: "zit",
  medium_city: "medium_city",
  rural_area: "rural_area",
};

export const loginEnum = {
  email: "email",
  password: "password",
};

export const projectParcipiantEnum = {
  form_submission: "form_submission",
  date_of_signing_agreement: "date_of_signing_agreement",
  years_age: "years_age",
  months_age: "months_age",
  education: "education",
  disability: "disability",
  disability_level: "disability_level",
  market_status: "market_status",
  working_person: "working_person",
  working_company_adress: "working_company_adress",
  working_street: "working_street",
  working_street_number: "working_street_number",
  working_zip_code: "working_zip_code",
  working_city: "working_city",
  working_workplace: "working_workplace",
  working_classification: "working_classification",
  working_classification_other: "working_classification_other",
  working_period_from: "working_period_from",
  working_period_to: "working_period_to",
  working_type: "working_type",
  working_type_nip: "working_type_nip",
  unemployment: "unemployment",
  months_of_unemployment: "months_of_unemployment",
  bank_account_number: "bank_account_number",
  national_minority: "national_minority",
  homeless: "homeless",
  adverse_social_situation: "adverse_social_situation",
  ct9: "ct9",
  penalty_of_liberty: "penalty_of_liberty",
  farming: "farming",
  social_security: "social_security",
};

export const ComponentEnum = {
  FormInput: "FormInput",
  FormCheckbox: "FormCheckbox",
  FormConditionalTextField: "FormConditionalTextField",
  FormDatePicker: "FormDatePicker",
  FormRadio: "FormRadio",
  FormSelect: "FormSelect",
  FormSwitch: "FormSwitch",
  FormInputMask: "FormInputMask",
  FormHeader: "FormHeader",
  FormSubHeader: "FormSubHeader",
};
