export const enum personalEnum {
  last_name = "last_name",
  first_name = "first_name",
  pesel = "pesel",
  date_of_birth = "date_of_birth",
  place_of_birth = "place_of_birth",
  gender = "gender",
  phone_number = "phone_number",
  email = "email",
  street = "street",
  street_number = "street_number",
  apartment_number = "apartment_number",
  city = "city",
  zip_code = "zip_code",
  county = "county",
  community = "community",
  voivodeship = "voivodeship",
  mailing_address = "mailing_address",
  mailing_street = "mailing_street",
  mailing_street_number = "mailing_street_number",
  mailing_apartment_number = "mailing_apartment_number",
  mailing_city = "mailing_city",
  mailing_zip_code = "mailing_zip_code",
  mailing_county = "mailing_county",
  mailing_community = "mailing_community",
  mailing_voivodeship = "mailing_voivodeship",
  black_list = "black_list",
  marketing_agreement = "marketing_agreement",
  shiping_agreement = "shiping_agreement",
  assigned_project = "assigned_project",
  sub_region = "sub_region",
  osi = "osi",
  zit = "zit",
  medium_city = "medium_city",
  rural_area = "rural_area",
}

export const enum ComponentEnum {
  FormInput = "FormInput",
  FormCheckbox = "FormCheckbox",
  FormConditionalTextField = "FormConditionalTextField",
  FormDatePicker = "FormDatePicker",
  FormRadio = "FormRadio",
  FormSelect = "FormSelect",
  FormSwitch = "FormSwitch",
  FormInputMask = "FormInputMask",
}
