export const personalEnum = {
  last_name: "last_name",
  first_name: "first_name",
  pesel: "pesel",
  date_of_birth: "date_of_birth",
  place_of_birth: "place_of_birth",
  gender: "gender",
  phone_number: "phone_number",
  email: "email",
  street: "street",
  street_number: "street_number",
  apartment_number: "apartment_number",
  city: "city",
  zip_code: "zip_code",
  county: "county",
  community: "community",
  voivodeship: "voivodeship",
  mailing_address: "mailing_address",
  mailing_street: "mailing_street",
  mailing_street_number: "mailing_street_number",
  mailing_apartment_number: "mailing_apartment_number",
  mailing_city: "mailing_city",
  mailing_zip_code: "mailing_zip_code",
  mailing_county: "mailing_county",
  mailing_community: "mailing_community",
  mailing_voivodeship: "mailing_voivodeship",
  black_list: "black_list",
  marketing_agreement: "marketing_agreement",
  shipping_agreement: "shipping_agreement",
  assigned_project: "assigned_project",
  sub_region: "sub_region",
  osi: "osi",
  zit: "zit",
  medium_city: "medium_city",
  rural_area: "rural_area",
};

export const loginEnum = {
  email: "email",
  password: "password",
};

export const ComponentEnum = {
  FormInput: "FormInput",
  FormCheckbox: "FormCheckbox",
  FormConditionalTextField: "FormConditionalTextField",
  FormDatePicker: "FormDatePicker",
  FormRadio: "FormRadio",
  FormSelect: "FormSelect",
  FormSwitch: "FormSwitch",
  FormInputMask: "FormInputMask",
};

export const trainingEnum = {
  name: "name",
  group_number: "group_number",
  start_training: "start_training",
  end_training: "end_training",
  hours_training: "hours_training",
  coach: "coach",
  examiner: "examiner",
  place: "place",
  street: "street",
  house_number: "house_number",
  apartment_number: "apartment_number",
  city: "city",
  business: "business",
  medicine_work: "medicine_work",
  health_department: "health_department",
  psychological: "psychological",
  registration_zus: "registration_zus",
  announcement_zus: "announcement_zus",
  nnw_start: "nnw_start",
  nnw_end: "nnw_end",
  digital_competence: "digital_competence",
  complete_training: "complete_training",
  date_of_exam: "date_of_exam",
  score_of_exam: "score_of_exam",
  qualified: "qualified",
  hours_of_attendance_with_l4: "hours_of_attendance_with_l4",
  hours_of_attendance_without_l4: "hours_of_attendance_without_l4",
  hours_to_zus: "hours_to_zus",
  scholarship: "scholarship",
  scholarship_from: "scholarship_from",
  scholarship_to: "scholarship_to",
  scholarship_sum: "scholarship_sum",
  scholarship_paid: "scholarship_paid",
  scholarship_date: "scholarship_date",
  travel_cost: "travel_cost",
  travel_cost_from: "travel_cost_from",
  travel_cost_to: "travel_cost_to",
  travel_cost_sum: "travel_cost_sum",
  travel_cost_paid: "travel_cost_paid",
  travel_cost_date: "travel_cost_date",
  cost_of_care: "cost_of_care",
  cost_of_care_from: "cost_of_care_from",
  cost_of_care_to: "cost_of_care_to",
  cost_of_care_sum: "cost_of_care_sum",
  cost_of_care_paid: "cost_of_care_paid",
  cost_of_care_date: "cost_of_care_date",
  attendance_list: "attendance_list",
  class_diary: "class_diary",
  catering_confirmation: "catering_confirmation",
  receipt_of_attestation_confirmation: "receipt_of_attestation_confirmation",
  attestation: "attestation",
  attestation_copy: "attestation_copy",
  exam_certificate: "exam_certificate",
  certificate_received: "certificate_received",
  certificate_copy: "certificate_copy",
  receipt_of_certificate_confirmation: "receipt_of_certificate_confirmation",
  exam_report: "exam_report",
  travel_cost_request: "travel_cost_request",
  care_cost_request: "care_cost_request",
  statement_to_policy_nnw: "statement_to_policy_nnw",
  evaluation_survey: "evaluation_survey",
  comments: "comments",
};

export const jobIntermendiationEnum = {
  session: "session",
  type_of_brokerage: "type_of_brokerage",
  employment_agent: "employment_agent",
  street: "street",
  house_number: "house_number",
  apartment_number: "apartment_number",
  city: "city",
  date_of_meeting: "date_of_meeting",
  start_of_meeting: "start_of_meeting",
  end_of_meeting: "end_of_meeting",
  duration_of_meeting: "duration_of_meeting",
  pp_card: "pp_card",
};

export const internshipEnum = {
  start_insurance_nnw: "start_insurance_nnw",
  end_insurance_nnw: "end_insurance_nnw",
  extension_nnw_to: "extension_nnw_to",
  application_to_zus: "application_to_zus",
  submission_from_zus: "submission_from_zus",
  data_of_signing_internship_contract: "data_of_signing_internship_contract",
  start_internship: "start_internship",
  end_internship: "end_internship",
  extension_of_internship: "extension_of_internship",
  occupational_medicine_research: "occupational_medicine_research",
  workspace_during_internship: "workspace_during_internship",
  zip_code: "zip_code",
  city: "city",
  street: "street",
  house_number: "house_number",
  apartment_number: "apartment_number",
  nip: "nip",
  internship_place: "internship_place",
  internship_zip_code: "internship_zip_code",
  internship_city: "internship_city",
  internship_street: "internship_street",
  internship_house_number: "internship_house_number",
  internship_apartment_number: "internship_apartment_number",
  working_hours: "working_hours",
  start_of_work: "start_of_work",
  internship_position: "internship_position",
  supervisor_first_name: "supervisor_first_name",
  supervisor_last_name: "supervisor_last_name",
  supervisor_from: "supervisor_from",
  supervisor_to: "supervisor_to",
  supervisor_email: "supervisor_email",
  supervisor_phone_number: "supervisor_phone_number",
  internship_contract: "internship_contract",
  policy_nnw: "policy_nnw",
  policy_statement: "policy_statement",
  occupational_medicine_examination: "occupational_medicine_examination",
  internship_supervisor_documents: "internship_supervisor_documents",
  date: "date",
  controlling: "controlling",
  inspection_scheduling_hours: "inspection_scheduling_hours",
  control_date: "control_date",
  current_supervisor: "current_supervisor",
  supervisor_name: "supervisor_name",
  intern_during_inspection: "intern_during_inspection",
  design_poster: "design_poster",
  control_survey: "control_survey",
  comments: "comments",
  vacation: "vacation",
  selected: "selected",
  number_of_vacation_days_per_day: "number_of_vacation_days_per_day",
  start: "start",
  end: "end",
  attendance_list: "attendance_list",
  vacation_request: "vacation_request",
  sick_leave: "sick_leave",
  application_for_travel_expenses: "application_for_travel_expenses",
  application_for_care_costs: "application_for_care_costs",
  days_worked_without_l4: "days_worked_without_l4",
  days_on_l4: "days_on_l4",
  days_of_absence_free_of_charge: "days_of_absence_free_of_charge",
  days_to_calculate_zus: "days_to_calculate_zus",
  scholarship_paid: "scholarship_paid",
  scholarship_amount_paid: "scholarship_amount_paid",
  travel_cost: "travel_cost",
  travel_cost_from: "travel_cost_from",
  travel_cost_to: "travel_cost_to",
  travel_cost_paid: "travel_cost_paid",
  cost_of_care: "cost_of_care",
  cost_of_care_from: "cost_of_care_from",
  cost_of_care_to: "cost_of_care_to",
  cost_of_care_paid: "cost_of_care_paid",
  employers_opinion: "employers_opinion",
  participant_survey: "participant_survey",
  internship_certificate: "internship_certificate",
  return_of_medical_examination: "return_of_medical_examination",
};

export const takingUpEmploymentEnum = {
  taking_up_employment: "taking_up_employment",
  date_of_signing_contract: "date_of_signing_contract",
  start_contract_time: "start_contract_time",
  end_contract_time: "end_contract_time",
  type_of_contract: "type_of_contract",
  working_time: "working_time",
  up_to_4_weeks: "up_to_4_weeks",
  up_to_3_months: "up_to_3_months",
  subject_matter_agreement: "subject_matter_agreement",
  continuation_after_3_months: "continuation_after_3_months",
  change_form_of_employment: "change_form_of_employment",
  company_name: "company_name",
  zip_code: "zip_code",
  city: "city",
  street: "street",
  number: "number",
  nip: "nip",
  position: "position",
};

export const endParticipationProjectEnum = {
  end_of_project: "end_of_project",
  compatible_path: "compatible_path",
  supporting_document: "supporting_document",
  document_date: "document_date",
  supporting_document_to_3_month: "supporting_document_to_3_month",
};

export const payoutsEnum = {
  type_of_list: "type_of_list",
  project: "project",
  training: "training",
  group_number: "group_number",
  start_term: "start_term",
  end_term: "end_term",
  payroll_number: "payroll_number",
  date_of_issue: "date_of_issue",
};
