import { personalEnum } from "../enum";
import { ILogin } from "./validator";

export const defaultValues: ILogin = {
  [personalEnum.last_name]: "",
  [personalEnum.first_name]: "",
  [personalEnum.pesel]: "",
  [personalEnum.date_of_birth]: new Date(),
  [personalEnum.place_of_birth]: "",
  [personalEnum.gender]: "",
  [personalEnum.phone_number]: "",
  [personalEnum.email]: "",
  [personalEnum.street]: "",
  [personalEnum.street_number]: "",
  [personalEnum.apartment_number]: "",
  [personalEnum.city]: "",
  [personalEnum.zip_code]: "",
  [personalEnum.county]: "",
  [personalEnum.community]: "",
  [personalEnum.voivodeship]: "",
  [personalEnum.mailing_address]: "",
  [personalEnum.mailing_street]: "",
  [personalEnum.mailing_street_number]: "",
  [personalEnum.mailing_apartment_number]: "",
  [personalEnum.mailing_city]: "",
  [personalEnum.mailing_zip_code]: "",
  [personalEnum.mailing_county]: "",
  [personalEnum.mailing_community]: "",
  [personalEnum.mailing_voivodeship]: "",
  [personalEnum.black_list]: "",
  [personalEnum.marketing_agreement]: "",
  [personalEnum.shiping_agreement]: "",
  [personalEnum.assigned_project]: "",
  [personalEnum.sub_region]: "",
  [personalEnum.osi]: "",
  [personalEnum.medium_city]: "",
  [personalEnum.rural_area]: "",
};
