import { personalEnum } from "../enum";
import { IValidator } from "./validator";

export const defaultValues: IValidator = {
  [personalEnum.last_name]: "",
  [personalEnum.first_name]: "",
  [personalEnum.pesel]: "",
  [personalEnum.date_of_birth]: new Date(),
  [personalEnum.place_of_birth]: "",
  [personalEnum.gender]: 1,
  [personalEnum.phone_number]: "",
  [personalEnum.email]: "",
  [personalEnum.street]: "",
  [personalEnum.street_number]: "",
  [personalEnum.apartment_number]: "",
  [personalEnum.city]: "",
  [personalEnum.zip_code]: "",
  [personalEnum.county]: "",
  [personalEnum.community]: "",
  [personalEnum.voivodeship]: "",
  [personalEnum.mailing_address]: 0,
  [personalEnum.mailing_street]: "",
  [personalEnum.mailing_street_number]: "",
  [personalEnum.mailing_apartment_number]: "",
  [personalEnum.mailing_city]: "",
  [personalEnum.mailing_zip_code]: "",
  [personalEnum.mailing_county]: "",
  [personalEnum.mailing_community]: "",
  [personalEnum.mailing_voivodeship]: "",
  [personalEnum.assigned_project]: 1,
  [personalEnum.black_list]: 0,
  [personalEnum.marketing_agreement]: 0,
  [personalEnum.shiping_agreement]: 0,
  [personalEnum.sub_region]: 0,
  [personalEnum.osi]: 0,
  [personalEnum.zit]: 0,
  [personalEnum.medium_city]: 0,
  [personalEnum.rural_area]: 0,
};
