import { projectEnum } from "../enum";

export const defaultValues = {
    [projectEnum.name]: "",
    [projectEnum.number]: "",
    [projectEnum.beneficiary]: "",
    [projectEnum.beneficiary_for]: "",
    [projectEnum.partner]: "",
    [projectEnum.partner_for]: "",
    [projectEnum.start_project]: "",
    [projectEnum.end_project]: "",
    [projectEnum.extension]: "",
    [projectEnum.contract_number]: "",
    [projectEnum.contract_date]: "",
    [projectEnum.operational_programme]: "",
    [projectEnum.guardian]: "",
    [projectEnum.guardian_from]: "",
    [projectEnum.guardian_to]: "",
    [projectEnum.manager]: "",
    [projectEnum.manager_from]: "",
    [projectEnum.manager_to]: "",
    [projectEnum.coordinator_first_name]: "",
    [projectEnum.coordinator_last_name]: "",
    [projectEnum.coordinator_from]: "",
    [projectEnum.coordinator_to]: "",
    [projectEnum.authorized_to_sl_lsi]: "",
    [projectEnum.bank_access]: "",
    [projectEnum.web_page]: "",
    [projectEnum.project_email]: "",
    [projectEnum.zus_rate]: "",
    [projectEnum.rate_per_hour]: "",
    [projectEnum.internship_rate]: "",
    [projectEnum.theme_area]: "",
    [projectEnum.market_status]: "",
    [projectEnum.osi]: "",
    [projectEnum.sub_region]: "",
    [projectEnum.medium_city]: "",
    [projectEnum.zit]: "",
    [projectEnum.reckoning]: "",
};
