import { projectParticipantEnum } from "../enum";

export const defaultValues = {
  [projectParticipantEnum.form_submission]: new Date(),
  [projectParticipantEnum.date_of_signing_agreement]: new Date(),
  [projectParticipantEnum.years_age]: "",
  [projectParticipantEnum.months_age]: "",
  [projectParticipantEnum.education]: 1,
  [projectParticipantEnum.disability]: 1,
  [projectParticipantEnum.disability_level]: 1,
  [projectParticipantEnum.market_status]: 1,
  [projectParticipantEnum.working_person]: 1,
  [projectParticipantEnum.working_company_address]: "",
  [projectParticipantEnum.working_street]: "",
  [projectParticipantEnum.working_street_number]: "",
  [projectParticipantEnum.working_zip_code]: "",
  [projectParticipantEnum.working_city]: "",
  [projectParticipantEnum.working_workplace]: "",
  [projectParticipantEnum.working_classification]: 1,
  [projectParticipantEnum.working_classification_other]: "",
  [projectParticipantEnum.working_period_from]: new Date(),
  [projectParticipantEnum.working_period_to]: new Date(),
  [projectParticipantEnum.working_type]: 1,
  [projectParticipantEnum.working_type_nip]: "",
  [projectParticipantEnum.unemployment]: 1,
  [projectParticipantEnum.months_of_unemployment]: "",
  [projectParticipantEnum.bank_account_number]: "",
  [projectParticipantEnum.national_minority]: 0,
  [projectParticipantEnum.homeless]: 0,
  [projectParticipantEnum.adverse_social_situation]: 0,
  [projectParticipantEnum.ct9]: 0,
  [projectParticipantEnum.penalty_of_liberty]: 0,
  [projectParticipantEnum.farming]: 0,
  [projectParticipantEnum.social_security]: 0,
};
