import { projectParcipiantEnum } from "../enum";
import { IValidator } from "./validator";

export const defaultValues: IValidator = {
  [projectParcipiantEnum.form_submission]: new Date(),
  [projectParcipiantEnum.date_of_signing_agreement]: new Date(),
  [projectParcipiantEnum.years_age]: "",
  [projectParcipiantEnum.months_age]: "",
  [projectParcipiantEnum.education]: 1,
  [projectParcipiantEnum.disability]: 1,
  [projectParcipiantEnum.disability_level]: 1,
  [projectParcipiantEnum.market_status]: 1,
  [projectParcipiantEnum.working_person]: 1,
  [projectParcipiantEnum.working_company_adress]: "",
  [projectParcipiantEnum.working_street]: "",
  [projectParcipiantEnum.working_street_number]: "",
  [projectParcipiantEnum.working_zip_code]: "",
  [projectParcipiantEnum.working_city]: "",
  [projectParcipiantEnum.working_workplace]: "",
  [projectParcipiantEnum.working_classification]: 1,
  [projectParcipiantEnum.working_classification_other]: "",
  [projectParcipiantEnum.working_period_from]: new Date(),
  [projectParcipiantEnum.working_period_to]: new Date(),
  [projectParcipiantEnum.working_type]: 1,
  [projectParcipiantEnum.working_type_nip]: "",
  [projectParcipiantEnum.unemployment]: 1,
  [projectParcipiantEnum.months_of_unemployment]: "",
  [projectParcipiantEnum.bank_account_number]: "",
  [projectParcipiantEnum.national_minority]: 0,
  [projectParcipiantEnum.homeless]: 0,
  [projectParcipiantEnum.adverse_social_situation]: 0,
  [projectParcipiantEnum.ct9]: 0,
  [projectParcipiantEnum.penalty_of_liberty]: 0,
  [projectParcipiantEnum.farming]: 0,
  [projectParcipiantEnum.social_security]: 0,
};
