import { newProjectEnum } from "../enum";

export const defaultValues = {
    [newProjectEnum.name]: "",
    [newProjectEnum.number]: "",
    [newProjectEnum.beneficiary]: "",
    [newProjectEnum.beneficiary_for]: "",
    [newProjectEnum.partner]: "",
    [newProjectEnum.partner_for]: "",
    [newProjectEnum.start_project]: "",
    [newProjectEnum.end_project]: "",
    [newProjectEnum.extension]: "",
    [newProjectEnum.contract_number]: "",
    [newProjectEnum.contract_date]: "",
    [newProjectEnum.operational_programme]: "",
    [newProjectEnum.guardian]: "",
    [newProjectEnum.guardian_from]: "",
    [newProjectEnum.guardian_to]: "",
    [newProjectEnum.manager]: "",
    [newProjectEnum.manager_from]: "",
    [newProjectEnum.manager_to]: "",
    [newProjectEnum.coordinator_first_name]: "",
    [newProjectEnum.coordinator_last_name]: "",
    [newProjectEnum.coordinator_from]: "",
    [newProjectEnum.coordinator_to]: "",
    [newProjectEnum.authorized_to_sl_lsi]: "",
    [newProjectEnum.bank_access]: "",
    [newProjectEnum.web_page]: "",
    [newProjectEnum.project_email]: "",
    [newProjectEnum.zus_rate]: "",
    [newProjectEnum.rate_per_hour]: "",
    [newProjectEnum.internship_rate]: "",
    [newProjectEnum.theme_area]: "",
    [newProjectEnum.market_status]: "",
    [newProjectEnum.osi]: "",
    [newProjectEnum.sub_region]: "",
    [newProjectEnum.medium_city]: "",
    [newProjectEnum.zit]: "",
    [newProjectEnum.reckoning]: "",
};
